# Generated by Django 2.0.5 on 2018-07-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20180728_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Feature',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
