# Generated by Django 2.0.5 on 2018-07-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='Title',
            field=models.CharField(max_length=40),
        ),
    ]
